apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: promtail
  namespace: monitoring
spec:
  interval: 5m
  timeout: 2m
  chart:
    spec:
      chart: promtail
      version: "6.16.0"
      interval: 5m
      sourceRef:
        kind: HelmRepository
        name: grafana
  values:
    resources:
      requests:
        cpu: 20m
        memory: 100Mi
      limits:
        cpu: 100m
        memory: 1000Mi