apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: metrics-server
  namespace: kube-system
spec:
  interval: 10m
  timeout: 5m
  chart:
    spec:
      chart: metrics-server
      version: "3.12.0"
      interval: 5m
      sourceRef:
        kind: HelmRepository
        name: kube-metrics-server
  values:
    replicas: 1
    containerPort: 4443
    resources:
      requests:
        cpu: 100m
        memory: 200Mi
      limits:
        cpu: 200m
        memory: 400Mi
    nodeSelector:
      nodegroup: "k8s-core"

