apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: mscoin-eks-apps
  namespace: flux-system
spec:
  interval: 1m0s
  url: ssh://git@github.com/Davidgoodman2333/mscoin-eks-apps.git
  ref:
    branch: main
  secretRef:
    name: git-secret

