apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: autoscaler
  namespace: kube-system
spec:
  interval: 10m
  timeout: 5m
  chart:
    spec:
      chart: cluster-autoscaler
      version: "9.37.0"
      interval: 5m
      sourceRef:
        kind: HelmRepository
        name: kube-autoscaler
  values:
    fullnameOverride: aws-cluster-autoscaler
    awsRegion: ap-east-1
    rbac:
      serviceAccount:
        create: true
        name: tf-service-role-for-cluster-autoscaler
        annotations:
          eks.amazonaws.com/role-arn: arn:aws:iam::457591490960:role/tf-service-role-for-cluster-autoscaler
    autoDiscovery:
      cloudProvider: aws
      clusterName: mscoin-data-prod-eks
    resources:
      requests:
        cpu: 10m
        memory: 50Mi
      limits:
        cpu: 20m
        memory: 100Mi
    nodeSelector:
      nodegroup: "k8s-core"
