apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: aws-load-balancer
  namespace: kube-system
spec:
  interval: 5m0s
  timeout: 30s
  chart:
    spec:
      chart: aws-load-balancer-controller
      version: 1.8.0
      interval: 5m0s
      sourceRef:
        kind: HelmRepository
        name: eks
  values:
    replicaCount: 1
    fullnameOverride: "aws-load-balancer-controller"
    enableCertManager: false
    serviceMonitor:
      enabled: true
    clusterName: mscoin-data-prod-eks
    serviceAccount:
      create: true
      name: tf-service-role-for-load-balancer
      annotations:
        eks.amazonaws.com/role-arn: arn:aws:iam::457591490960:role/tf-service-role-for-load-balancer
    resources:
      requests:
        cpu: 10m
        memory: 50Mi
      limits:
        cpu: 20m
        memory: 500Mi
    nodeSelector:
      nodegroup: "k8s-core"
