apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-dns
  namespace: kube-system
spec:
  interval: 5m
  timeout: 2m
  chart:
    spec:
      chart: external-dns
      version: "1.14.4"
      interval: 5m
      sourceRef:
        kind: HelmRepository
        name: external-dns
  values:
    serviceAccount:
      create: true
      name: tf-service-role-for-external-dns
      annotations:
        eks.amazonaws.com/role-arn: arn:aws:iam::457591490960:role/tf-service-role-for-external-dns
    aws:
      zoneType: private
    domainFilters: ["mscoin-data.com"]
    resources:
      requests:
        cpu: 10m
        memory: 50Mi
      limits:
        cpu: 20m
        memory: 100Mi
    nodeSelector:
      nodegroup: "k8s-core"
