apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: mscoin-eks-apps-kustomization
  namespace: flux-system
spec:
  interval: 2m
  timeout: 1m
  sourceRef:
    kind: GitRepository
    name: mscoin-eks-apps
  path: "/"
  prune: true